basePath: '{{.BasePath}}'
definitions:
  casbinService.AddCasbinStruct:
    properties:
      v0:
        description: role_key
        minLength: 3
        type: string
      v1:
        description: path
        minLength: 4
        type: string
      v2:
        description: method
        minLength: 2
        type: string
    required:
    - v0
    - v1
    - v2
    type: object
  common.Response:
    properties:
      code:
        type: integer
      data:
        type: object
      msg:
        type: string
    type: object
  reportService.ReportStruct:
    properties:
      activity_id:
        type: integer
      name:
        minLength: 1
        type: string
      phone:
        minLength: 4
        type: string
    required:
    - name
    - phone
    type: object
  roleService.CreateRoleStruct:
    properties:
      remark:
        description: 备注
        maxLength: 100
        minLength: 4
        type: string
      role_key:
        maxLength: 10
        minLength: 4
        type: string
      role_name:
        description: 角色名称
        maxLength: 10
        minLength: 4
        type: string
    required:
    - role_key
    - role_name
    type: object
  roleService.UpdateRoleStruct:
    properties:
      remark:
        description: 备注
        maxLength: 100
        minLength: 4
        type: string
      role_name:
        description: 角色名称
        maxLength: 10
        minLength: 4
        type: string
    required:
    - role_name
    type: object
  userService.AddUserStruct:
    properties:
      password:
        minLength: 4
        type: string
      role_id:
        type: integer
      user_name:
        minLength: 4
        type: string
    required:
    - password
    - user_name
    type: object
  userService.AuthStruct:
    properties:
      password:
        minLength: 4
        type: string
      user_name:
        minLength: 4
        type: string
    required:
    - password
    - user_name
    type: object
  userService.ChangePasswordStruct:
    properties:
      new_password:
        minLength: 6
        type: string
      old_password:
        minLength: 4
        type: string
    required:
    - new_password
    - old_password
    type: object
host: '{{.Host}}'
info:
  contact: {}
  description: '{{.Description}}'
  license:
    name: MIT
    url: https://github.com/fanhengyuan/gin-web-admin/blob/master/LICENSE
  termsOfService: https://github.com/fanhengyuan/gin-web-admin
  title: '{{.Title}}'
  version: '{{.Version}}'
paths:
  /casbin:
    get:
      consumes:
      - application/json
      description: 获取规则列表
      parameters:
      - description: page number
        in: query
        name: p
        required: true
        type: integer
      - description: page limit
        in: query
        name: "n"
        required: true
        type: integer
      - description: v0 根据 role key 分组
        in: query
        name: group_by
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/common.Response'
            type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/common.Response'
            type: object
      security:
      - ApiKeyAuth: []
      summary: 规则列表
      tags:
      - Casbin
    post:
      consumes:
      - application/json
      description: 创建规则
      parameters:
      - description: create new user
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/casbinService.AddCasbinStruct'
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/common.Response'
            type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/common.Response'
            type: object
      security:
      - ApiKeyAuth: []
      summary: 创建规则
      tags:
      - Casbin
  /casbin/{id}:
    delete:
      consumes:
      - application/json
      description: 删除规则信息
      parameters:
      - description: casbin_id
        in: path
        name: id
        required: true
        type: integer
      - description: 删除规则
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/casbinService.AddCasbinStruct'
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/common.Response'
            type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/common.Response'
            type: object
      security:
      - ApiKeyAuth: []
      summary: 删除规则
      tags:
      - Casbin
    put:
      consumes:
      - application/json
      description: 修改规则信息
      parameters:
      - description: casbin_id
        in: path
        name: id
        required: true
        type: integer
      - description: 修改规则
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/casbinService.AddCasbinStruct'
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/common.Response'
            type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/common.Response'
            type: object
      security:
      - ApiKeyAuth: []
      summary: 修改规则
      tags:
      - Casbin
  /login:
    post:
      consumes:
      - application/json
      description: 用户登录
      parameters:
      - description: user login
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/userService.AuthStruct'
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/common.Response'
            type: object
      summary: User Login
      tags:
      - Auth
  /report:
    post:
      consumes:
      - application/json
      description: User Report Information
      parameters:
      - description: 上报信息
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/reportService.ReportStruct'
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/common.Response'
            type: object
      summary: Report Information
      tags:
      - Report
  /role:
    get:
      consumes:
      - application/json
      description: 获取角色表
      parameters:
      - description: page number
        in: query
        name: p
        required: true
        type: integer
      - description: page limit
        in: query
        name: "n"
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/common.Response'
            type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/common.Response'
            type: object
      security:
      - ApiKeyAuth: []
      summary: 角色列表
      tags:
      - Role
    post:
      consumes:
      - application/json
      description: 添加角色
      parameters:
      - description: role_id
        in: path
        name: role_id
        required: true
        type: integer
      - description: 添加
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/roleService.CreateRoleStruct'
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/common.Response'
            type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/common.Response'
            type: object
      security:
      - ApiKeyAuth: []
      summary: 添加角色
      tags:
      - Role
  /role/{role_id}:
    delete:
      consumes:
      - application/json
      description: 删除角色
      parameters:
      - description: role_id
        in: path
        name: role_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/common.Response'
            type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/common.Response'
            type: object
      security:
      - ApiKeyAuth: []
      summary: 删除角色
      tags:
      - Role
    put:
      consumes:
      - application/json
      description: 修改角色信息
      parameters:
      - description: role_id
        in: path
        name: role_id
        required: true
        type: integer
      - description: 修改角色
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/roleService.UpdateRoleStruct'
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/common.Response'
            type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/common.Response'
            type: object
      security:
      - ApiKeyAuth: []
      summary: 修改角色
      tags:
      - Role
  /sys/router:
    get:
      consumes:
      - application/json
      description: get router list
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/common.Response'
            type: object
      security:
      - ApiKeyAuth: []
      summary: 后端存在路由列表
      tags:
      - SYS
  /test/font:
    get:
      parameters:
      - description: base64 string
        in: query
        name: base64
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/common.Response'
            type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/common.Response'
            type: object
      security:
      - ApiKeyAuth: []
      summary: Base64 Decode
      tags:
      - Test
  /test/ping:
    get:
      consumes:
      - application/json
      description: Test Ping
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/common.Response'
            type: object
      security:
      - ApiKeyAuth: []
      summary: Ping
      tags:
      - Test
  /user:
    get:
      consumes:
      - application/json
      description: 获取用户列表
      parameters:
      - description: page number
        in: query
        name: p
        required: true
        type: integer
      - description: page limit
        in: query
        name: "n"
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/common.Response'
            type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/common.Response'
            type: object
      security:
      - ApiKeyAuth: []
      summary: 用户列表
      tags:
      - User
    post:
      consumes:
      - application/json
      description: 创建新用户
      parameters:
      - description: create new user
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/userService.AddUserStruct'
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/common.Response'
            type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/common.Response'
            type: object
      security:
      - ApiKeyAuth: []
      summary: 创建用户
      tags:
      - User
  /user/change_password:
    put:
      consumes:
      - application/json
      description: 密码修改
      parameters:
      - description: user change password
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/userService.ChangePasswordStruct'
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/common.Response'
            type: object
      security:
      - ApiKeyAuth: []
      summary: 修改密码
      tags:
      - User
  /user/logged_in:
    get:
      consumes:
      - application/json
      description: 当前登录用户信息
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/common.Response'
            type: object
      security:
      - ApiKeyAuth: []
      summary: 当前登录用户信息
      tags:
      - User
  /user/logout:
    put:
      consumes:
      - application/json
      description: 用户登出
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/common.Response'
            type: object
      security:
      - ApiKeyAuth: []
      summary: User Logout
      tags:
      - User
securityDefinitions:
  ApiKeyAuth:
    in: 'header like: Bearer xxxx'
    name: Authorization
    type: apiKey
swagger: "2.0"
